site_name: XCONFIGURE
site_author: Hans Pabst
copyright: Copyright (c) 2013-2024, XCONFIGURE <a href="https://xconfigure.readthedocs.io/LICENSE/">Contributors</a>.
site_description: High-Performance configuration patterns and recipes.
repo_url: https://github.com/hfp/xconfigure
edit_uri: edit/main/config
site_url: https://xconfigure.readthedocs.io/
docs_dir: config

markdown_extensions:
- toc:
    permalink: True
    toc_depth: 2
    title: None
extra_css:
- style.css

theme:
    name: readthedocs
    custom_dir: .theme

nav:
- index.md
- Applications:
  - CP2K: cp2k/README.md
  - LIBXSMM: libxsmm/README.md
  - LIBINT: libint/README.md
  - PLUMED: plumed/README.md
  - LIBMED: libmed/README.md
  - LIBXC: libxc/README.md
  - METIS: metis/README.md
  - HDF5: hdf5/README.md
  - ELPA: elpa/README.md
  - Vc: vc/README.md
- About:
  - Contributing: CONTRIBUTING.md
  - License: LICENSE.md
